"use client";

import type { NorthBlock, NorthStepDef } from "@/north/schema";

export const MARCO_ZERO_STEPS: NorthStepDef[] = [
  // ——— Seção 1: Sua Jornada até Aqui ———
  {
    key: "jornada",
    title: "Sua Jornada até Aqui",
    moduleSlug: "marco-zero",
    lessonSlug: "ws-marco-zero-jornada",
    blocks: [
      {
        type: "intro",
        title: "Sua Jornada até Aqui",
        description:
          "Antes de qualquer estratégia, precisamos conhecer você. Responda com sinceridade total — não existe resposta certa ou errada aqui. Escreva como se estivesse contando para alguém de confiança.",
      },
      {
        type: "field",
        fieldId: "s1_1",
        label: "Qual é a sua história como empresário(a)?",
        helperText: "Como tudo começou? De onde você veio, o que viveu, o que te trouxe até aqui.",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_2",
        label: "Qual foi o momento exato em que você decidiu construir isso?",
        helperText: "Tinha um gatilho, uma dor, uma visão? Conte esse momento com detalhes.",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_3",
        label: "Qual foi o período mais difícil da sua jornada — e como você superou?",
        helperText: "Não o que parece bonito contar, mas o que foi real e pesado.",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_4",
        label: "Em quais áreas você tem experiência ou conhecimento especializado?",
        helperText: "Pode incluir formação, mas principalmente o que você aprendeu fazendo.",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_5",
        label: "Quais são suas paixões e interesses — dentro e fora do negócio?",
        helperText: "O que te move além do trabalho? O que você faria mesmo sem receber?",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_6",
        label: "Quais são os valores inegociáveis na forma como você conduz seu negócio?",
        helperText: "O que você jamais abriria mão, mesmo sob pressão?",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_7",
        label: "Qual é o seu propósito como empresário(a)?",
        helperText: "Não o da empresa — o seu. O que te faz levantar nos dias difíceis?",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_8",
        label: "Qual é o propósito da sua empresa?",
        helperText: "Por que ela existe? Qual problema ela resolve no mundo?",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_9",
        label: "Na sua opinião, por que alguém te escolhe em vez do concorrente?",
        helperText: "Não o que você gostaria que fosse — o que você realmente acredita que faz a diferença.",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_10",
        label: "O que seus clientes dizem quando recomendam você ou te agradecem?",
        helperText: "As palavras exatas que eles usam. Se tiver prints ou depoimentos, use-os aqui.",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_11",
        label: "O que você quer que as pessoas sintam quando pensam em você e no que construiu?",
        helperText: "Não o que elas falam — o que elas sentem.",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s1_12",
        label: "Qual é a sua maior expectativa com o Método COMPASS?",
        helperText: "O que precisa acontecer aqui para você sentir que valeu cada minuto investido?",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
    ],
  },
  // ——— Seção 2: Seus Desafios Hoje ———
  {
    key: "desafios",
    title: "Seus Desafios Hoje",
    moduleSlug: "marco-zero",
    lessonSlug: "ws-marco-zero-desafios",
    blocks: [
      {
        type: "intro",
        title: "Seus Desafios Hoje",
        description:
          "Marque tudo que ressoa com a sua realidade atual. Seja honesto — quanto mais claro você for aqui, mais preciso será o seu caminho no método.",
      },
      { type: "intro", title: "Posicionamento", description: undefined },
      {
        type: "field",
        fieldId: "s2_1",
        label: "Posicionamento",
        fieldType: "multiChoice",
        required: false,
        options: [
          { id: "nao_sei_diferenca", label: "Não sei exatamente o que me diferencia dos concorrentes" },
          { id: "dificuldade_explicar", label: "Tenho dificuldade de explicar o que faço de forma clara e rápida" },
          { id: "genérico", label: "Me sinto genérico — parece que todo mundo faz o mesmo que eu" },
          { id: "nao_sei_para_quem", label: "Não sei para quem exatamente devo falar" },
          { id: "nao_soou_verdadeiro", label: "Já tentei me posicionar, mas não soou verdadeiro" },
        ],
      },
      { type: "intro", title: "Criação de conteúdo", description: undefined },
      {
        type: "field",
        fieldId: "s2_2",
        label: "Criação de conteúdo",
        fieldType: "multiChoice",
        required: false,
        options: [
          { id: "nao_sei_postar", label: "Não sei o que postar ou por onde começar" },
          { id: "travado_camera", label: "Fico travado na frente da câmera ou na hora de escrever" },
          { id: "posto_irregular", label: "Posto de forma irregular — quando lembro ou quando dá" },
          { id: "nao_sei_resultado", label: "Não sei se meu conteúdo está gerando resultado" },
          { id: "conteudo_sem_vendas", label: "Produzo conteúdo mas não vejo retorno em vendas" },
          { id: "sem_tempo", label: "Não tenho tempo para criar conteúdo com consistência" },
          { id: "copio_concorrentes", label: "Copio o que os concorrentes fazem sem ter uma estratégia própria" },
        ],
      },
      { type: "intro", title: "Vendas online", description: undefined },
      {
        type: "field",
        fieldId: "s2_3",
        label: "Vendas online",
        fieldType: "multiChoice",
        required: false,
        options: [
          { id: "nao_sei_transformar", label: "Não sei como transformar seguidores em clientes" },
          { id: "presenca_nao_vende", label: "Tenho presença digital mas ela não gera vendas" },
          { id: "dependia_indicacao", label: "Dependia de indicações e não sei como mudar isso" },
          { id: "trafego_sem_resultado", label: "Já investi em tráfego pago e não tive resultado" },
          { id: "medo_vendedor", label: "Tenho medo de parecer chato ou vendedor demais" },
          { id: "sem_processo", label: "Não tenho um processo claro de como vender pelo digital" },
        ],
      },
      { type: "intro", title: "Mentalidade e execução", description: undefined },
      {
        type: "field",
        fieldId: "s2_4",
        label: "Mentalidade e execução",
        fieldType: "multiChoice",
        required: false,
        options: [
          { id: "sei_mas_nao_executo", label: "Sei o que preciso fazer mas não consigo executar" },
          { id: "agencia_decepcionou", label: "Já contratei agência ou freelancer e me decepcionei" },
          { id: "medo_ser_julgado", label: "Tenho medo de aparecer e ser julgado" },
          { id: "nao_preparado", label: "Não me sinto preparado o suficiente para me expor" },
          { id: "nao_mantenho_consistencia", label: "Começo com energia mas não mantenho a consistência" },
          { id: "marketing_nao_funciona", label: "Sinto que marketing digital não funciona para o meu negócio" },
        ],
      },
      {
        type: "field",
        fieldId: "s2_5",
        label: "Como você se sente em relação a vender online hoje?",
        helperText:
          "Descreva o seu momento atual com honestidade. O que está funcionando, o que não está, e o que você sente quando pensa em vender pelo digital.",
        fieldType: "longText",
        required: true,
        minRows: 3,
        placeholder: "Escreva aqui…",
      },
      {
        type: "intro",
        title: "Seu nível de familiaridade com tecnologia",
        description:
          "Avalie cada área honestamente — isso vai definir como o método vai ser aplicado com você.",
      },
      {
        type: "field",
        fieldId: "s2_6",
        label: "Inteligência Artificial (ChatGPT, Claude, Gemini, etc.)",
        fieldType: "scaleChoice",
        required: true,
        scaleRows: [{ id: "ia", label: "Inteligência Artificial (ChatGPT, Claude, Gemini, etc.)" }],
        scaleOptions: [
          { id: "nunca", label: "Nunca usei" },
          { id: "pouco", label: "Já ouvi falar mas uso pouco" },
          { id: "ocasional", label: "Uso ocasionalmente mas sem método" },
          { id: "regular", label: "Uso com regularidade e já vejo resultado" },
          { id: "domino", label: "Domino e integro no meu dia a dia" },
        ],
      },
      {
        type: "field",
        fieldId: "s2_7",
        label: "Automações (WhatsApp, e-mail, CRM, fluxos)",
        fieldType: "scaleChoice",
        required: true,
        scaleRows: [{ id: "auto", label: "Automações (WhatsApp, e-mail, CRM, fluxos)" }],
        scaleOptions: [
          { id: "nunca", label: "Nunca usei" },
          { id: "ouvi_falar", label: "Já ouvi falar mas nunca implementei" },
          { id: "basico", label: "Tenho algo básico configurado" },
          { id: "consistencia", label: "Uso automações com consistência" },
          { id: "estruturado", label: "Tenho fluxos estruturados e funcionando" },
        ],
      },
      {
        type: "field",
        fieldId: "s2_8",
        label: "Ferramentas digitais (Canva, edição de vídeo, agendadores, analytics)",
        fieldType: "scaleChoice",
        required: true,
        scaleRows: [{ id: "ferr", label: "Ferramentas digitais (Canva, edição de vídeo, agendadores, analytics)" }],
        scaleOptions: [
          { id: "basico", label: "Uso o básico do básico" },
          { id: "me_viro", label: "Me viro mas sem domínio real" },
          { id: "razoavel", label: "Tenho habilidade razoável em algumas ferramentas" },
          { id: "domino_principais", label: "Domino bem as principais ferramentas" },
          { id: "fluencia", label: "Tenho fluência digital — aprendo rápido qualquer ferramenta" },
        ],
      },
      {
        type: "intro",
        title: "Seus Sonhos e Visão de Futuro",
        description:
          "Agora o lado oposto — não o que te trava, mas o que te move. Responda sem filtro.",
      },
      {
        type: "field",
        fieldId: "s2_9",
        label: "O que você mais deseja conquistar nos próximos 12 meses?",
        helperText: "Pessoal e profissional — tudo conta.",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s2_10",
        label: "Onde você quer estar daqui a 3 anos — no negócio e na vida?",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s2_11",
        label: "O que seria sucesso real para você — não para os outros, para você?",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s2_12",
        label: "O que você definitivamente NÃO quer — no negócio, no marketing, na vida?",
        fieldType: "longText",
        required: true,
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s2_13",
        label: "No digital, o que você mais deseja conquistar? (marque até 3)",
        fieldType: "multiChoiceLimit",
        required: false,
        maxSelections: 3,
        options: [
          { id: "vender_instagram", label: "Vender mais pelo Instagram sem depender de agência" },
          { id: "audiencia_fiel", label: "Construir uma audiência fiel e engajada" },
          { id: "referencia", label: "Ser reconhecido como referência no meu nicho" },
          { id: "processo_previsivel", label: "Ter um processo de vendas previsível e consistente" },
          { id: "liberdade_criar", label: "Ter liberdade para criar conteúdo sem travar" },
          { id: "negocio_sem_mim", label: "Fazer meu negócio funcionar mesmo quando não estou presente" },
          { id: "reduzir_indicacao", label: "Reduzir dependência de indicações e tráfego pago" },
          { id: "lançar_produto", label: "Lançar um produto ou serviço digital" },
          { id: "escalar_faturamento", label: "Escalar o faturamento mantendo a qualidade" },
          { id: "outro", label: "Outro", inlineOpen: true },
        ],
      },
    ],
  },
  // ——— Seção 3: Diagnóstico do Negócio ———
  {
    key: "diagnostico",
    title: "Diagnóstico do Negócio",
    moduleSlug: "marco-zero",
    lessonSlug: "ws-marco-zero-diagnostico",
    blocks: [
      {
        type: "intro",
        title: "Diagnóstico do negócio",
        description:
          "Vamos registrar informações essenciais sobre empresa, mercado e público. Salve como rascunho e evolua aos poucos.",
      },
      {
        type: "field",
        fieldId: "s3_texto_apresentacao",
        label: "Texto de apresentação",
        helperText: "Fale sobre sua empresa, o que ela faz, valores, missão e visão.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s3_analise_mercado",
        label: "Análise de mercado",
        helperText: "A análise de mercado ajuda a entender o setor, tendências e público-alvo.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s3_concorrentes",
        label: "Cite 5 concorrentes",
        helperText: "Liste empresas, projetos ou negócios que são seus concorrentes.",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "s3_principais_produtos",
        label: "Seus principais produtos/serviços",
        helperText: "Liste quais são seus principais produtos e/ou serviços.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s3_mais_lucrativo",
        label: "Dentro desses produtos/serviços, qual é o mais lucrativo?",
        helperText: "Liste por ordem de lucratividade (maior lucro primeiro).",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s3_ticket_medio",
        label: "Ticket médio (valor médio por venda)",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "table",
        fieldId: "s3_plataformas_links",
        label: "Em quais plataformas você está presente?",
        helperText: "Indique links ou @ dos seus perfis / páginas.",
        columns: [
          { key: "platform", label: "Plataforma", placeholder: "Ex.: Instagram" },
          { key: "link", label: "Link / @", placeholder: "https://... ou @usuario" },
        ],
        fixedRows: [
          { key: "instagram", label: "Instagram" },
          { key: "youtube", label: "YouTube" },
          { key: "tiktok", label: "TikTok" },
          { key: "linkedin", label: "LinkedIn" },
          { key: "site", label: "Site" },
          { key: "whatsapp_business", label: "WhatsApp Business" },
          { key: "outro", label: "Outro" },
        ],
      },
      { type: "divider" },
      { type: "intro", title: "Dados demográficos do seu público" },
      {
        type: "field",
        fieldId: "s3_publico_regiao",
        label: "De qual região o seu público alvo faz parte?",
        fieldType: "singleChoice",
        options: [
          { id: "local", label: "Local (no seu bairro ou na sua cidade)" },
          { id: "regional", label: "Regional (cidades/estados próximos)" },
          { id: "nacional", label: "Nacional (todo o país)" },
        ],
      },
      {
        type: "field",
        fieldId: "s3_faixa_etaria",
        label: "Qual a faixa etária?",
        helperText: "Pode marcar mais de uma.",
        fieldType: "multiChoice",
        options: [
          { id: "18_24", label: "18 a 24 anos" },
          { id: "25_34", label: "25 a 34 anos" },
          { id: "35_44", label: "35 a 44 anos" },
          { id: "45_54", label: "45 a 54 anos" },
          { id: "55_64", label: "55 a 64 anos" },
          { id: "65_plus", label: "Mais de 65 anos" },
        ],
      },
      {
        type: "field",
        fieldId: "s3_faixa_etaria_principal",
        label: "E qual a principal faixa etária?",
        fieldType: "shortText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s3_genero",
        label: "Qual o gênero predominante?",
        fieldType: "singleChoice",
        options: [
          { id: "homem", label: "Homem" },
          { id: "mulher", label: "Mulher" },
          { id: "ambos", label: "Ambos" },
        ],
      },
      {
        type: "table",
        fieldId: "s3_renda",
        label: "Renda individual e familiar",
        columns: [
          { key: "tipo", label: "Tipo", placeholder: "Renda individual" },
          { key: "valor", label: "Valor", placeholder: "R$ 0,00" },
        ],
      },
      { type: "divider" },
      { type: "intro", title: "Empresa e negócio" },
      {
        type: "field",
        fieldId: "s3_cidade_estado",
        label: "Cidade e estado",
        helperText: "Onde fica a sede da empresa? Tem filiais?",
        fieldType: "shortText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s3_tempo_mercado",
        label: "Tempo de mercado",
        helperText: "Há quanto tempo está no mercado (formal ou informalmente)?",
        fieldType: "shortText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s3_faturamento_mes",
        label: "Faturamento do último mês",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "field",
        fieldId: "s3_faturamento_trimestre",
        label: "Faturamento do último trimestre (3 meses)",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "field",
        fieldId: "s3_faturamento_ano",
        label: "Faturamento do último ano",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "field",
        fieldId: "s3_melhores_meses",
        label: "Melhores meses de vendas (sazonalidade)",
        fieldType: "multiChoice",
        options: [
          { id: "jan", label: "Janeiro" },
          { id: "fev", label: "Fevereiro" },
          { id: "mar", label: "Março" },
          { id: "abr", label: "Abril" },
          { id: "mai", label: "Maio" },
          { id: "jun", label: "Junho" },
          { id: "jul", label: "Julho" },
          { id: "ago", label: "Agosto" },
          { id: "set", label: "Setembro" },
          { id: "out", label: "Outubro" },
          { id: "nov", label: "Novembro" },
          { id: "dez", label: "Dezembro" },
        ],
      },
      { type: "divider" },
      { type: "intro", title: "Marketing" },
      {
        type: "field",
        fieldId: "s3_marketing_estrutura",
        label: "Como funciona hoje sua estrutura de Marketing?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s3_marketing_investimento",
        label: "Valor aproximado investido em Marketing mensalmente",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      { type: "divider" },
      { type: "intro", title: "Nível de tecnologia e ferramentas" },
      {
        type: "field",
        fieldId: "s3_nivel_tecnologia",
        label: "Como você avalia seu uso de tecnologia e ferramentas?",
        helperText: "Para cada item, indique o nível: Nunca usei → Domino.",
        fieldType: "scaleChoice",
        scaleRows: [
          { id: "ia", label: "Inteligência Artificial (IA)" },
          { id: "automacoes", label: "Automações" },
          { id: "ferramentas", label: "Ferramentas de gestão/vendas" },
        ],
        scaleOptions: [
          { id: "nunca", label: "Nunca usei" },
          { id: "iniciante", label: "Iniciante" },
          { id: "intermediario", label: "Intermediário" },
          { id: "avancado", label: "Avançado" },
          { id: "domino", label: "Domino" },
        ],
      },
      { type: "divider" },
      { type: "intro", title: "Análise SWOT" },
      {
        type: "field",
        fieldId: "s3_swot_forcas",
        label: "Forças",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "s3_swot_oportunidades",
        label: "Oportunidades",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "s3_swot_fraquezas",
        label: "Fraquezas",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "s3_swot_ameacas",
        label: "Ameaças",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
    ],
  },
  // ——— Seção 4: Produtos e Serviços ———
  {
    key: "produtos",
    title: "Produtos e Serviços",
    moduleSlug: "marco-zero",
    lessonSlug: "ws-marco-zero-produtos",
    blocks: [
      {
        type: "intro",
        title: "Produtos e Serviços",
        description:
          "Detalhe seus produtos e serviços, modelo de atuação e como você entrega valor ao cliente.",
      },
      {
        type: "field",
        fieldId: "s4_tipo_negocio",
        label: "Seu negócio é predominantemente:",
        fieldType: "singleChoice",
        options: [
          { id: "produto", label: "Produto (venda de bens físicos ou digitais)" },
          { id: "servico", label: "Serviço" },
          { id: "misto", label: "Misto (produto + serviço)" },
        ],
      },
      {
        type: "field",
        fieldId: "s4_misto_detalhe",
        label: "Descreva como é a mistura (produto + serviço)",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
        showWhen: { fieldId: "s4_tipo_negocio", value: "misto" },
      },
      {
        type: "field",
        fieldId: "s4_principal_produto_servico",
        label: "Qual seu principal produto ou serviço?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s4_catalogo",
        label: "Liste seus principais itens (catálogo ou linha de serviços)",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "s4_modelo_comercial_produto",
        label: "Como você vende esse produto? (modelo comercial)",
        helperText: "Ex.: venda única, assinatura, recorrência, marketplaces.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
        showWhen: { fieldId: "s4_tipo_negocio", value: "produto" },
      },
      {
        type: "field",
        fieldId: "s4_modelo_comercial_servico",
        label: "Como você entrega e cobra esse serviço? (modelo comercial)",
        helperText: "Ex.: por projeto, por hora, pacotes, retainer.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
        showWhen: { fieldId: "s4_tipo_negocio", value: "servico" },
      },
      {
        type: "field",
        fieldId: "s4_modelo_comercial_misto",
        label: "Como funciona seu modelo comercial (produto + serviço)?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
        showWhen: { fieldId: "s4_tipo_negocio", value: "misto" },
      },
      {
        type: "field",
        fieldId: "s4_preco_medio",
        label: "Preço médio do seu principal produto/serviço",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "field",
        fieldId: "s4_entregavel",
        label: "O que o cliente recebe ao fechar com você? (entregável)",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
    ],
  },
  // ——— Seção 5: Identidade e Direção ———
  {
    key: "identidade",
    title: "Identidade e Direção",
    moduleSlug: "marco-zero",
    lessonSlug: "ws-marco-zero-identidade",
    blocks: [
      {
        type: "intro",
        title: "Identidade e Direção",
        description:
          "Defina identidade da marca, posicionamento e metas para os próximos períodos.",
      },
      {
        type: "field",
        fieldId: "s5_posicionamento",
        label: "Como você quer ser percebido(a) no mercado? (posicionamento)",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s5_diferencial",
        label: "Qual seu principal diferencial em uma frase?",
        fieldType: "shortText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "s5_objetivo_faturamento",
        label: "Qual seu objetivo de faturamento para os próximos 12 meses?",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "field",
        fieldId: "s5_objetivo_quantitativo",
        label: "Algum outro objetivo quantitativo? (ex.: número de clientes, ticket médio)",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
    ],
  },
];
