"use client";

import type { NorthBlock, NorthStepDef } from "@/north/schema";

export const MARCO_ZERO_STEPS: NorthStepDef[] = [
  {
    key: "jornada",
    title: "Sua Jornada até aqui",
    moduleSlug: "marco-zero",
    lessonTitleIncludes: "Marco Zero",
    blocks: [
      {
        type: "intro",
        title: "Sua Jornada até aqui",
        description:
          "O propósito aqui é saber quem é você de verdade. Aqui não existem respostas erradas. Responda de peito aberto, trazendo sentimentos, anseios, desejos e o que pensa sobre cada assunto.",
      },
      {
        type: "field",
        fieldId: "marcoZero_historia_empresario",
        label: "Qual a minha história como empresário(a)?",
        helperText:
          "Qual é a história da sua empresa/negócio? Como sua empresa começou? O que te motivou a abrir a empresa?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_experiencia_conhecimento",
        label: "Em quais áreas eu tenho experiência ou conhecimento especializado?",
        helperText:
          "O que você faz e que é bom? Quais dessas coisas você já faz na sua empresa? Em que você é bom além do que faz na empresa?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_paixoes_interesses",
        label: "Quais são as minhas paixões e interesses pessoais?",
        helperText:
          "O que você mais gosta de fazer? Quais áreas te instigam a aprender mais e se aperfeiçoar?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_proposito_pessoal",
        label: "Qual seu propósito?",
        helperText:
          "O que faz você acordar de manhã todos os dias e te move para enfrentar seus desafios rumo aos seus sonhos?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_proposito_empresa",
        label: "Qual o propósito da empresa/projeto?",
        helperText: "Qual a transformação ou solução você oferece para o seu cliente?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_o_que_vende",
        label: "O que você vende?",
        helperText: "Dê mais detalhes sobre o seu produto ou serviço.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_cliente_ideal",
        label: "Quem é seu cliente ideal?",
        helperText: "Descreva como se fosse uma pessoa que você conhece muito bem.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_por_que_melhor",
        label: "Como e por quê você é melhor?",
        helperText: "Por que as pessoas deveriam comprar de você e não de um concorrente?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_cliente_especial",
        label: "Como você faz seu cliente se sentir especial?",
        helperText: "O que você faz de diferente para que seu cliente se sinta visto, percebido?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "marcoZero_historia_cliente_conta",
        label: "Qual história seu cliente irá contar sobre você?",
        helperText: "Como seu cliente deveria falar sobre você para outra pessoa?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      { type: "divider" },
      {
        type: "intro",
        title: "Posição inicial",
        description:
          "Esse é o momento de registrar a sua história. Precisamos saber onde você está hoje, com muita sinceridade.",
      },
      {
        type: "field",
        fieldId: "marcoZero_posicao_inicial",
        label: "Posição inicial",
        helperText: "Descreva onde você está hoje e o contexto atual do seu negócio.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
    ],
  },
  {
    key: "diagnosticoNegocio",
    title: "Diagnóstico do negócio",
    moduleSlug: "marco-zero",
    lessonTitleIncludes: "1. Diagnóstico",
    blocks: [
      {
        type: "intro",
        title: "Diagnóstico do negócio",
        description:
          "Vamos registrar informações essenciais sobre empresa, mercado e público. Salve como rascunho e evolua aos poucos.",
      },
      {
        type: "field",
        fieldId: "diag_texto_apresentacao",
        label: "Texto de apresentação",
        helperText: "Fale sobre sua empresa, o que ela faz, valores, missão e visão.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "diag_analise_mercado",
        label: "Análise de mercado",
        helperText: "A análise de mercado ajuda a entender o setor, tendências e público-alvo.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "diag_empresas_nicho",
        label: "Cite 5 empresas do mesmo nicho",
        helperText: "Liste empresas que você se inspira.",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "diag_concorrentes",
        label: "Cite 5 concorrentes",
        helperText: "Liste empresas, projetos ou negócios que são seus concorrentes.",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "diag_principais_produtos",
        label: "Seus principais produtos/serviços",
        helperText: "Liste quais são seus principais produtos e/ou serviços.",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "diag_mais_lucrativo",
        label: "Dentro desses produtos/serviços, qual é o mais lucrativo?",
        helperText: "Liste por ordem de lucratividade (maior lucro primeiro).",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "table",
        fieldId: "diag_plataformas_links",
        label: "Em quais plataformas você está presente?",
        helperText: "Indique links dos seus perfis / páginas.",
        columns: [
          { key: "platform", label: "Plataforma", placeholder: "Ex.: Instagram" },
          { key: "link", label: "Link", placeholder: "https://..." },
        ],
      },
      { type: "divider" },
      { type: "intro", title: "Dados demográficos do seu público" },
      {
        type: "field",
        fieldId: "diag_publico_regiao",
        label: "De qual região o seu público alvo faz parte?",
        fieldType: "singleChoice",
        options: [
          { id: "local", label: "Local (no seu bairro ou na sua cidade)" },
          { id: "regional", label: "Regional (cidades/estados próximos)" },
          { id: "nacional", label: "Nacional (todo o país)" },
        ],
      },
      {
        type: "field",
        fieldId: "diag_faixa_etaria",
        label: "Qual a faixa etária?",
        helperText: "Pode marcar mais de uma.",
        fieldType: "multiChoice",
        options: [
          { id: "18_24", label: "18 a 24 anos" },
          { id: "25_34", label: "25 a 34 anos" },
          { id: "35_44", label: "35 a 44 anos" },
          { id: "45_54", label: "45 a 54 anos" },
          { id: "55_64", label: "55 a 64 anos" },
          { id: "65_plus", label: "Mais de 65 anos" },
        ],
      },
      {
        type: "field",
        fieldId: "diag_faixa_etaria_principal",
        label: "E qual a principal faixa etária?",
        fieldType: "shortText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "diag_genero",
        label: "Qual o gênero predominante?",
        fieldType: "singleChoice",
        options: [
          { id: "homem", label: "Homem" },
          { id: "mulher", label: "Mulher" },
          { id: "ambos", label: "Ambos" },
        ],
      },
      {
        type: "table",
        fieldId: "diag_renda",
        label: "Renda individual e familiar",
        columns: [
          { key: "tipo", label: "Tipo", placeholder: "Renda individual" },
          { key: "valor", label: "Valor", placeholder: "R$ 0,00" },
        ],
      },
      { type: "divider" },
      { type: "intro", title: "Empresa e negócio" },
      {
        type: "field",
        fieldId: "diag_cidade_estado",
        label: "Cidade e estado",
        helperText: "Onde fica a sede da empresa? Tem filiais?",
        fieldType: "shortText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "diag_tempo_mercado",
        label: "Tempo de mercado",
        helperText: "Há quanto tempo está no mercado (formal ou informalmente)?",
        fieldType: "shortText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "diag_faturamento_mes",
        label: "Faturamento do último mês",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "field",
        fieldId: "diag_faturamento_trimestre",
        label: "Faturamento do último trimestre (3 meses)",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "field",
        fieldId: "diag_faturamento_ano",
        label: "Faturamento do último ano",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      {
        type: "field",
        fieldId: "diag_melhores_meses",
        label: "Melhores meses de vendas (sazonalidade)",
        fieldType: "multiChoice",
        options: [
          { id: "jan", label: "Janeiro" },
          { id: "fev", label: "Fevereiro" },
          { id: "mar", label: "Março" },
          { id: "abr", label: "Abril" },
          { id: "mai", label: "Maio" },
          { id: "jun", label: "Junho" },
          { id: "jul", label: "Julho" },
          { id: "ago", label: "Agosto" },
          { id: "set", label: "Setembro" },
          { id: "out", label: "Outubro" },
          { id: "nov", label: "Novembro" },
          { id: "dez", label: "Dezembro" },
        ],
      },
      { type: "divider" },
      { type: "intro", title: "Marketing" },
      {
        type: "field",
        fieldId: "diag_marketing_estrutura",
        label: "Como funciona hoje sua estrutura de Marketing?",
        fieldType: "longText",
        placeholder: "Escreva aqui…",
      },
      {
        type: "field",
        fieldId: "diag_marketing_investimento",
        label: "Valor aproximado investido em Marketing mensalmente",
        fieldType: "currency",
        placeholder: "R$ 0,00",
      },
      { type: "divider" },
      { type: "intro", title: "Análise SWOT" },
      {
        type: "field",
        fieldId: "diag_swot_forcas",
        label: "Forças",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "diag_swot_oportunidades",
        label: "Oportunidades",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "diag_swot_fraquezas",
        label: "Fraquezas",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
      {
        type: "field",
        fieldId: "diag_swot_ameacas",
        label: "Ameaças",
        fieldType: "stringList",
        placeholder: "Digite e pressione Enter…",
      },
    ],
  },
];

